name: CI

on:
  push:
    branches: [main, feature.*]
    tags: ['v*.*.*']
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with: {dotnet-version: 8.x}
    - run: dotnet build --framework net6.0
    - run: dotnet build --framework net6.0-windows7.0

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: dotnet tool restore
    - run: dotnet csharpier --check .

  release:
    needs: [build, format]
    if: "startsWith(github.ref, 'refs/tags/') && github.event.repository.fork == false"
    permissions:
      contents: write
    uses: ./.github/workflows/release.yaml
    secrets: inherit
