name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with: {dotnet-version: 8.x}
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}    
    - run: dotnet pack

    - name: publish
      run: dotnet nuget push bin\Release\*.nupkg
